# 메인 파일 이름을 지정하세요.
main_file = 'main.py'# fill here

# 데이타 파일들을 지정하세요.
data_files = [
    # fill here
    'ball21x21.png','bird_animation.png','ENCR10B.TTF','enemy.png',
    'field_test2.png','grass.png','sonic_animation.png'

]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
    # fill here

]

